### ISSUE TITLE
Swift on Linux

### ISSUE THREAD

**Issue by appsbg** [alexeyxo/protobuf-swift#111]
I have this strange behavior. Why after I use parseFromData I always get "Foundation.NSString" instead of the real string?
```
let p = try CommonClasses.Test.Builder()
p.client = "test"
p.id = 1
print(p.client) // outputs: test
print(p.id) // outputs: 1

let s = try CommonClasses.Test.parseFromData(p.build().data())
print(s.client) // outputs: Foundation.NSString
print(s.id) // outputs: 1
```

My proto file:
```
package CommonClasses;

message Test {
required string client = 1;
required int32 id = 1;
}

```

**Comment by alexeyxo** [comment]
Try with last commit. Currently I can't run unittests on Linux.

**Comment by appsbg** [comment]
It still doesn't work. Now I cannot compile because String bytesNoCopy and String data are non-optionals. But even when I remove the I now the output is: "(0x0000000000946c92, 4, 4, false)"

**Comment by alexeyxo** [comment]
Why you can't compile?

**Comment by appsbg** [comment]
CodedInputStream.swift:529:26: error: cannot force unwrap value of non-optional type 'String'
            return result!

CodedInputStream.swift:535:70: error: cannot force unwrap value of non-optional type 'String'
            return String(data: data, encoding: NSUTF8StringEncoding)!

**Comment by appsbg** [comment]
As I told you, if I remove the unwrapping operator it compiles, but I get  "(0x0000000000946c92, 4, 4, false)" as output

**Comment by appsbg** [comment]
Interesting, it compiles with Xcode 7.3 beta, but not with swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04

**Comment by alexeyxo** [comment]
Because Xcode 7.3 distributed with Swift 2.1.

**Comment by appsbg** [comment]
Yes, it looks that in swift 2.2 those methods no longer return optionals anymore. But I still get strange output. What it could be?

**Comment by appsbg** [comment]
I fixed it myself. You can revert all changes and just do it like this:
    ```
  if (size <= (bufferSize - bufferPos) && size > 0)
        {
            let results:NSString = NSString(bytes: (buffer.mutableBytes + Int(bufferPos)), length: Int(size), encoding:  NSUTF8StringEncoding)!
            let result : String = String(results**.bridge()**)
            bufferPos += size
            return result
        }
        else
        {
            let data = try readRawData(size)
            let s = NSString(data: data, encoding: NSUTF8StringEncoding)!
            return String(s**.bridge()**)
        }
```

**Comment by appsbg** [comment]
This should be #if os(Linux)

**Comment by goloveychuk** [comment]
Do you waiting contributions or going to make it linux compatible by your own?

**Comment by alexeyxo** [comment]
I am waiting official release xCode 7.3.
